version: "3.8"

services:
        espia_server:
                container_name: espia_server
                restart: always
                image: ghcr.io/tomp332/espia-server:latest
                ports:
                        - 443:443
                volumes:
                        - type: bind
                          source: <your config.ini file>
                          target: /server/espia_server/configs/config.ini
                        - type: bind
                          source: <local dir absolute path for all user data>
                          target: /server/espia_server/app/uploads
